### ISSUE TITLE
merges to master are treated as SNAPSHOT

### ISSUE THREAD

**Issue by cfurst** [tschulte/gradle-semantic-release-plugin#41] opened 2020-08-18 22:48 UTC
Hello,
You documentation says the following:
```
Releases are only performed on certain branches (/master/ and /(?:release[-/])?\d+(?:.\d+)?.x/ by default). On other branches only SNAPSHOT versions are built. 
```
But when using the `release` task with our gradle build in our Jenkins CI server:
```
sh("gradle release -Dorg.ajoberstar.grgit.auth.username=${GH_TOKEN} -Dorg.ajoberstar.grgit.auth.password -DGH_TOKEN${GH_TOKEN}")
```
We are finding that some builds on the master branch are not creating releases but snapshots. For example in our build workflow we have the following checkout task:
```
git fetch --tags --progress https://github.bamtech.co/bamnet-search/full-text-discovery-api.git +refs/heads/master:refs/remotes/origin/master # timeout=10

Checking out Revision d23c9c1b836f71c3c41b3cb0cda50f098f471915 (master)
```
however later we find that the inferred release is a snapshot:
```
 gradle release -Dorg.ajoberstar.grgit.auth.username=**** -Dorg.ajoberstar.grgit.auth.password -DGH_TOKEN****



> Configure project :

Inferred version: 1.135.1-SNAPSHOT
```
We have a feeling that this is due to mal-formed commit messages. However, we feel that this is too strict a requirement for the plug-in to determine whether or not this is snapshot or not. If the build in on the master branch it should at least assume it's at least a patch version if the format is not followed. We also think that the format of the messages should be configurable for better flexibility.

**To reproduce:**
1. Configure the semantic plug as per your wiki
1. create a 1.0.0 version unless you have released before
1. create some feature branch and add some commits to it without following the message format described on your wiki (in our case we left out a colon - (yes, the lack of a colon broke our builds, thanks!)
1. merge/rebase/squash the feature branch to master and run the gradle  release task
1. a snapshot version should be inferred.

**Comment by error418** [comment] 2020-08-21 06:15
The commit message needs to comply to the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit) and must be of type `fix` or `feat` (and/or a Breaking Change).

If the commit messages do not match these requirements (or an other type is used), a snapshot-version will be generated. Make sure to lowercase the type and your checked out git repository has no uncommitted changes when running the release task.

Without the format semantic-release  no version can be determined. The developer needs to make the decision what type of change a commit represents and document it using the commit message format

#### For example
The developer makes a documentation change on a branch, which is merged into master using the `docs` type. Using your suggested approach a new version would be released, which is in this case unnecessary.

If the code was not touched the version should also not be touched.

**Comment by cfurst** [comment] 2020-08-30 03:43
You need to trust that the developer's workflow makes sense, not their commit messages. If I make a documentation change, why on earth would I execute the release task if there is no intention of releasing the code? This is what is great about gradle, I can build, test, and then `git push` any documentation changes without even needing to increment the semantic version. In fact since a documentation change is not, I would argue, a minor, major nor patch, there is no need for a release. 

Most developers use branches to determine what is released, when something is merged to master it is considered a release candidate or something that is deployed to some staged environment at least (a minor release). The point is, your docs say that it is the branches, not the commit message formats that determine the type of release it is, except in the case where the text `BREAKING CHANGE` APPEARS IN LETTERS LIKE THESE. I would argue that you should at least have some configuration that would use  the commit graph data from a particular branch you were building for whether or not this is a release candidate. We shouldn't have to stick to your commit message format just to get this thing to work if it doesn't suit our business needs. It nails your (otherwise brilliant) project into a corner that limits it use, IMO.

All you really need, is `breaking change` or BREAKING CHANGE, HELLO? and a branch to tell if this is a major or minor release. A patch? Most patches and fixes are done on via branches off of what's in prod anyway. How about we call the patch branch `Tech-Debt` and call it day?

**Comment by cfurst** [comment] 2020-09-25 15:19
So squash merge messages seem to break this, consider this message:
```
 feat(SEE-22): Limit participant billing order (#104)
    
    * feat(SEE-22): Limit participant billing order to 6 for sitesearch
    
    * feat(SEE-22): Constants for suggest vs site, broken down by participant categories
    
    * feat(SEE-22): Fixing constants and tests
    
    * feat(SEE-22): Changing defaults
    
    * feat(SEE-22): Fixing tests
```
This should up the minor version at least.. however when on master this is viewed as a snapshot.. well, it's not, not by your docs, not by anything described by Angular.. 

Any ideas?

**Comment by skannengiesser** [comment] 2020-09-26 10:26
Have you checked that all of the relevant factors as stated in the [Readme](https://github.com/tschulte/gradle-semantic-release-plugin/blame/master/README.md#L255-L258) are given?

E.g. your Gradle invocation might create files that are not in your .gitignore which makes the repo dirty and not qualify for a non snaphot release. Watch out for it in the logs.

Concerning your other statements. We are happily using this plugin for quite a while. Furthermore I'd suggest you read [this](https://www.conventionalcommits.org/en/v1.0.0/) to better understand the reasons for this kind of commit message format. If you disagree this plugin might not be suited for you.

**Comment by cfurst** [comment] 2020-09-26 15:11
We clean the workspace before every build. Have you found that squash merge messages don't mess things up? That's our working theory right now. I've read the whole angular conventional commits thing, I get it. However, there is something in the way the plugin analyzes messages that prevents it from determining that we are doing a release and not a snapshot. We will continue to investigate and post any relevant findings.

Thanks.

**Comment by skannengiesser** [comment] 2020-09-27 07:12
The plugin does of course also determine a correct version on squash commits. But speaking about squash commits. Why are you squashing these commits in your example? It looks as if all your commits stand for individual features. Squashing them will not lead to a complete changelog in your Github release.

**Comment by cfurst** [comment] 2020-09-27 11:22
They are merges into master. Each representing a project to be released. It fits our orgs coding and release workflow and I find it to be very useful in how commits are organized and represented.

**Comment by cfurst** [comment] 2020-09-28 15:18
Also another thing to consider is that this project was a forked project in github. Any idea if that might be throwing `grgit` off?

**Comment by cfurst** [comment] 2020-09-28 22:57
Ok we figured this out... 
It turns out that the Jenkins CI server we were doing this on was checking out a detached head:
```
currentBranch:org.ajoberstar.grgit.Branch(HEAD), repoDirty:false, nearestVersion:org.ajoberstar.gradle.git.release.semver.NearestVersion(1.61.0, 1.61.0, 5, 5), inferredNormal:null, inferredPreRelease:null, inferredBuildMetadata:null)
2020-09-28T20:47:48.218+0000 [INFO] [org.ajoberstar.gradle.git.release.base.ReleasePluginExtension] Falling back to default strategy: semantic-release-SNAPSHOT
...
+ git status
HEAD detached at 4445c26
nothing to commit, working tree clean
```
Now as you probably know `HEAD` is not a branch... it's just where the tip of the repo is pointing. I would argue that a warning should be given indicating the checkout is not a branch checkout, if branches are part of the deal here, so the user doesn't have to go nuts about this. However, representing `HEAD` inside of a `org.ajoberstar.grgit.Branch` class is probably more of a problem on the `grgit` side.

So we'll close on that note.. and thanks for listening.

**Comment by cfurst** [comment] 2020-09-29 15:39
So actually new developments really make me think that there is a bug in `SemanticReleaseChangeLogService` and thus I think this issue deserves revisiting:
This commit message:
`Revert "fix(SEE-269): Making image root a param in order to deploy past versions from old repo" `
with the `fix(See-269):` message header should have produced a patch... but
```
+ gradle release -Dorg.ajoberstar.grgit.auth.username=**** -Dorg.ajoberstar.grgit.auth.password -DGH_TOKEN****

> Configure project :
Inferred version: 1.61.7-SNAPSHOT
```
so something is wrong with the regex indeed. 
We can confirm this was on master because:
```
> Task :release
Pushing changes in [refs/heads/master] to origin
```

**Comment by tschulte** [comment] 2021-01-12 15:29
This is now a duplicate of #1.

**Closed as completed by tschulte** 2021-01-12 15:29 UTC
